### ISSUE TITLE
Include a few key commands

### ISSUE THREAD

**Issue by yagehu** [dep-sys/nix-dabei#10]
I would like to try this out with hcloud. Do you mind adding a couple of important commands to README so I can get started? Thanks!

**Comment by yagehu** [comment]
Something like this?

```
nix build .#hetznerInstaller
```

How would I copy the image to the host? Do I start the rescue system like [this](https://docs.hetzner.com/robot/dedicated-server/troubleshooting/hetzner-rescue-system/)?

**Comment by phaer** [comment]
Hello! Thanks for opening this issue, documentation is still an open TODO as this is pretty much work-in-progress. You should nevertheless be able to deploy a machine:

* First run `export HCLOUD_TOKEN="..."` or add it to your .envrc
* Then comment `x.instance-data.storedPath = ./hosts/my-little-webserver.json;` in examples/hetzner-hcloud/flake.nix.
*  finally run
```
nix develop
cd examples/hetzner-hcloud
nix build .#hetznerInstaller
./result/hcloud-create-machine.sh your-machine-name
```

This should deploy a working nixos on a new hcloud cx11 instance named `your machine name`, but currently assumes that your hcloud account already has your ssh pub key stored as "ssh key" and hard-codes cx11. 

Let me know if you run into any problems or have ideas for improvement. PRs welcome as well :)
