### ISSUE TITLE
Separate provisioning VM from copying disk image

### ISSUE THREAD

**Issue by yagehu** [dep-sys/nix-dabei#11]
Thanks for the tips in #10. Worked like a charm! In my case I provisioned the hcloud server in rescue mode with Terraform and manually executed the `rsync` and `hcloud-do-install.sh` commands:

https://github.com/dep-sys/nix-dabei/blob/1f55e54cf98bb491b05c0dd21684880af2bc7815/lib/providers/hcloud.nix#L56-L65

Are you open to a PR from me to separate the server provisioning in its own script? This allows people to provision the server however they want.

**Comment by phaer** [comment]
Hey @yagehu! Glad it did, I think you are the first user besides myself ;)
Yes, totally open for a PR separating the two. Also open for a ready to go terraform example, I've got a draft locally but my priorities shifted and I won't really find time to polish and test in in the coming weeks.

**Comment by phaer** [comment]
@yagehu I've just added some logic to allow using generic disk-images from githubs ci instead of a local build. I believe those changes should also allow for your use case? Just set `NO_UPLOAD=1` when running `hcloud-create-machine.sh`
